/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carreradeautos3;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import org.json.JSONException;

/**
 *
 * @author jebarest
 */
public class NombreArchivoGTablero extends javax.swing.JFrame {
String partida;
private static JLabel auto0, auto1, auto2, auto3, auto4,pt1,pt2,pt3,pt4,pt5;
private static int cantidad;
private static String name1,name2,name3,name4;
    /**
     * Creates new form NombreArchivoGTablero
     */
    public NombreArchivoGTablero( JLabel auto0,JLabel auto1,JLabel auto2,JLabel auto3,JLabel auto4,JLabel puntosA0,
            JLabel puntosA1,JLabel puntosA2,JLabel puntosA3,JLabel puntosA4,int cantidad,String name1,String name2,String name3,String name4) {
        initComponents();
        this.auto0=auto0;
        this.auto1=auto1;
        this.auto2=auto2;
        this.auto3=auto3;
        this.auto4=auto4;
        this.pt1=puntosA0;
        this.pt2=puntosA1;
        this.pt3=puntosA2;
        this.pt4=puntosA3;
        this.pt5=puntosA4;
        this.cantidad=cantidad;
        this.name1=name1;
        this.name2=name2;
        this.name3=name3;
        this.name4=name4;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Partida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre Partida");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Partida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Partida, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Partida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartidaActionPerformed
       
    }//GEN-LAST:event_PartidaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.partida=Partida.getText();
        GuardarTablero gt=new GuardarTablero();
      
        for (int i = 1; i <=cantidad; i++) {        
            switch (i) {
                case 1:
            {
                try {
                    gt.gtablero1(auto0, auto1,pt1,pt2,partida,name1);
                } catch (JSONException ex) {
                    Logger.getLogger(NombreArchivoGTablero.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                break;
                case 2:
            {
                try {
                    gt.gtablero2(auto0, auto1, auto2,pt1,pt2,pt3,partida,name1,name2);
                } catch (JSONException ex) {
                    Logger.getLogger(NombreArchivoGTablero.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                break;
                case 3:
            {
                try {
                    gt.gtablero3(auto0, auto1, auto2, auto3,pt1,pt2,pt3,pt4,partida,name1,name2,name3);
                } catch (JSONException ex) {
                    Logger.getLogger(NombreArchivoGTablero.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                break;
                case 4:
            {
                try {
                    gt.gtablero4(auto0, auto1, auto2, auto3, auto4,pt1,pt2,pt3,pt4,pt5,partida,name1,name2,name3,name4);
                } catch (JSONException ex) {
                    Logger.getLogger(NombreArchivoGTablero.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                    
                break;
            }
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NombreArchivoGTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NombreArchivoGTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NombreArchivoGTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NombreArchivoGTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NombreArchivoGTablero(auto0, auto1, auto2, auto3, auto4,pt1,pt2,pt3,pt4,pt5,cantidad,name1,name2,name3,name4).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Partida;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
